### ISSUE TITLE
support sequence

### ISSUE THREAD

**Issue by robertdiers** [opentestingapi/backlog#12]
a sequence of numbers as random values, based on existing value in random store (add x)

**Comment by BenjaminGDH** [comment]
thies means a pre-existing random variable e.g. <randomVar1>:= 10 can be leveraged to set another random variable <randomVar2>:= <randomVar1> + 2   ?

**Comment by robertdiers** [comment]
yes - based on "inheritValue" from last inject

**Comment by robertdiers** [comment]
done 1.37
