### ISSUE TITLE
inject with senddelay continues with follow-up check right away with no regard to the delay

### ISSUE THREAD

**Issue by BenjaminGDH** [opentestingapi/backlog#16]
Hi @robertdiers , currently an inject with a send delay configuration is directly moving on to the next check referenced within the inject. The message to be injected is correctly injected after the defined delay. But the follow-up checks after the inject which depend on the delayed message have been processed in the meantime during the delay. 
It would be great if the continuation of the follow up checks within a delayed inject can also be delayed, such that the next check will be triggered when the delayed message is injected. 

This way it will be easier to keep the overall testflow in sync. Otherwise the maxwaittime of the follow-up check could be increased to cover the delay time period. But this is from a test design perspective and from system usage not my prefered solution.

**Comment by BenjaminGDH** [comment]
@robertdiers OK

**Comment by robertdiers** [comment]
@BenjaminGDH as you can specify a longer duration for the check - what's the benefit? Delay is not designed to create workflows with it, it is designed to fix the race conditions when using Kafka. It is only the next check that need an increased maxwaitime, as subsequent ones will start later.

**Comment by robertdiers** [comment]
@BenjaminGDH please check my latest comment - I would like to close the issue with this explanation as it could be solved easily. Any other doubts?

**Comment by robertdiers** [comment]
API extension for chained injects might solve it:

1. injectid: myid
2. delay: 3s
3. amount: 1...n

**Comment by robertdiers** [comment]
Unfortunately, it is not feasible.
If the creation of the check objects is delayed (would be necessary), we create the same situation as before - race conditions are no longer recoverable. For planning the workflow we should not rely on the delay parameter, but the use of the cron annotation in conjunction with inheritFrom for random data.
