### ISSUE TITLE
support of placeholders or wildcards within validation files

### ISSUE THREAD

**Issue by BenjaminGDH** [opentestingapi/backlog#17]
Hi @robertdiers, currently validation files are set such that they define a specific known string that is matched against a response from a query against a specific application. The validation file content can be enriched with replacement variables that are dynamically created during test execution. 

Nevertheless, there are often cases were a request response contains values like timestamps that are created by the application and can't be known during test creation. These values often show up in the middle of a target substring that needs to be validated, and complicate or block a precise validation. 

Thus, it would be great if a placeholder or wildcard token can be introduced, which allows a certain sequence of any characters to occur over a defined length starting from the point the placeholder is located in a validation file.  

Example: 
application response contains:
`{"ereignisse":[{"status":"NACHRICHT_VERSANDT","zeitpunkt":"2023-02-08T07:39:47.255565Z","system":"SYS-1"},{"status":"VORGANG_AKTUALISIERT","zeitpunkt":"2023-02-08T07:39:14.794862Z","system":"SYS-2"},{"status":"VORGANG_ANGELEGT","zeitpunkt":"2023-02-08T07:39:14.240919Z","system":"SYS-3"}]}`

a check is planed that validates that there is a 'ereignisse' entry with `"system":"SYS-3"` and `"status":"VORGANG_AKTUALISIERT"` 

currently the check can't be implemented as intended. Only a workaround is possible which checks via the 2 following separate validation files that the seeked system value and status value show up in the response independently from each other. 

- validatition-file-1.txt --> `"system":"SYS-3"`
- validatition-file-2.txt --> `"status":"VORGANG_AKTUALISIERT"`

But this check will also pass if the entries show up in different entries like in the example above, and when it actually should have failed.

Therefore it would be helpful if the validation file supports placeholder or wildcard token as described above to precisely validate a target substring within a response with one validation file
- validatition-file.txt --> `{"status":"VORGANG_AKTUALISIERT","zeitpunkt":"##WILDCARD-WITH-LENGTH-27##","system":"SYS-3"}`

In this case ota would support the placeholder key word ##WILDCARD-WITH-LENGTH-27## which allows a sequence of any characters, e.g. `a-zA-Z0-9.:,;-_/\?!.....` with length 27 showing up at the position of the key word

**Comment by BenjaminGDH** [comment]
@robertdiers OK
testing wise this issue has the highest priority, since it will significantly improve the quality and clarity of our tests

**Comment by robertdiers** [comment]
Sadly JSON does not know a order of elements, so it really depends on the implementation of the services you are going to test. We should think about defining a real JSON and compare "JSON" style and not by String. It would also solve the issue, as contains would mean other values are allowed. But it will get complex if we talk about lists of objects as we could have an random order... @BenjaminGDH would it solve your use case? because random order might break this type of check...

**Comment by robertdiers** [comment]
Thinking about a JSON schema validation might also bring benefit for the users.

**Comment by robertdiers** [comment]
fixed with version 1.26 and API 1.1
